# ---const--- #
# FPS
FPS = 120
# move interval
SNAKE_MOVE_INTERVAL_MS = 130
ENEMY_SPAWN_INTERVAL_MS = 3000
BULLET_MOVE_INTERVAL_MS = 60

# grid
GRID_SIZE = 20
GRID_WIDTH = 60
GRID_HEIGHT = 50
# colour
BACKGROUND_COLOUR = (10, 10, 10)
SNAKE_COLOUR = (80, 220, 120)
ENEMY_SNAKE_COLOUR = (180, 60, 60)
MAP_COLOUR = (20, 20, 20)
TEXT_COLOUR = (30, 30, 30)
APPLE_COLOUR = (220, 60, 60)
WALL_COLOUR = (120, 120, 120)
ITEM_TAIL_CUT_COLOUR = (80, 160, 255)
GOLDEN_APPLE_COLOUR = (255, 215, 0)
PORTAL_COLOUR = (180, 80, 255)
BULLET_COLOUR = (255, 240, 120)
BULLET_SUPPLY_COLOUR = (255, 180, 80)

# UI COLOUR
UI_COLOUR = (18, 24, 28)
UI_BORDER_COLOUR = (170, 235, 85)
UI_TEXT_COLOUR = (170, 235, 85)  # green，content
UI_TITLE_COLOUR = (190, 255, 90)  # bright green，sub title
UI_ACCENT_COLOUR = (35, 225, 240)  # cyan blue，for TARGET / STATUS title
UI_MUTED_TEXT_COLOUR = (120, 160, 130)
# font
UI_FONT_PATH = "assets/fonts/PixeloidSans.ttf"
UI_BOLD_FONT_PATH = "assets/fonts/PixeloidSans-Bold.ttf"
UI_FONT_SIZE = 22
UI_TITLE_FONT_SIZE = 26
UI_SMALL_FONT_SIZE = 18

# --- layout --- #
LEFT_MARGIN = 40
TOP_MARGIN = 40
RIGHT_MARGIN = 40
BOTTOM_MARGIN = 40
UI_GAP = 40
# MAP width
MAP_WIDTH = GRID_SIZE * GRID_WIDTH
MAP_HEIGHT = GRID_SIZE * GRID_HEIGHT
# map left top corner
MAP_X = LEFT_MARGIN
MAP_Y = TOP_MARGIN
# UI
UI_WIDTH = MAP_WIDTH // 2
UI_HEIGHT = MAP_HEIGHT
UI_X = MAP_X + MAP_WIDTH + UI_GAP
UI_Y = MAP_Y
MAX_MSGS = 10
# pause menu overlay
PAUSE_OVERLAY_ALPHA = 200

PAUSE_MENU_TITLE_Y = 140
PAUSE_MENU_BUTTON_WIDTH = 300
PAUSE_MENU_BUTTON_HEIGHT = 140
PAUSE_MENU_BUTTON_GAP = 22
PAUSE_MENU_START_Y_OFFSET = 10
PAUSE_MENU_HINT_OFFSET_Y = 40
# screen
SCREEN_WIDTH = LEFT_MARGIN + MAP_WIDTH + UI_GAP + UI_WIDTH + RIGHT_MARGIN
SCREEN_HEIGHT = TOP_MARGIN + MAP_HEIGHT + BOTTOM_MARGIN

# adaptive window
WINDOW_WIDTH_RATIO = 0.94
WINDOW_HEIGHT_RATIO = 0.90

# participating logic code
# target

# TARGET_SEQUENCE = "ILOVEPYTHONCOMP9001"
TARGET_SEQUENCE = "ILOVEPYTHONCOMP9001"
# snake
INITIAL_SNAKE_BODY = [(GRID_WIDTH * 1 // 3, GRID_HEIGHT * 3 // 4)]
INITIAL_LIVES = 5
DIRECTIONS = {
    "UP": (0, -1),
    "DOWN": (0, 1),
    "LEFT": (-1, 0),
    "RIGHT": (1, 0),
}


# apple
MAX_APPLES = 18
APPLE_LIFETIME_MS = 10000  # apple lifetime
APPLE_LIFETIME_RANDOM_RANGE_MS = 4000  # random range

# enemy snake
ENEMY_MIN_LENGTH = 2
ENEMY_MIN_INITIAL_LENGTH = 2
ENEMY_MAX_INITIAL_LENGTH = 12
MAX_ENEMY_SNAKES = 8


ENEMY_MIN_STEPS = 4
ENEMY_MAX_STEPS = 12

# portal

# bullet
INITIAL_BULLETS = 15
BULLET_LIFETIME_MS = 8000

# bullet supply item
BULLET_SUPPLY_MIN_AMOUNT = 10
BULLET_SUPPLY_MAX_AMOUNT = 25
MAX_BULLET_SUPPLY_ITEMS = 3
BULLET_SUPPLY_SPAWN_INTERVAL_MS = 15000
