# ---const--- #
# grid
GRID_SIZE = 20
GRID_WIDTH = 40
GRID_HEIGHT = 40
# colour
BACKGROUND_COLOUR = (30, 30, 30)
SNAKE_COLOUR = (80, 220, 120)
MAP_COLOUR = (20, 20, 20)
UI_COLOUR = (245, 245, 245)
TEXT_COLOUR = (30, 30, 30)
APPLE_COLOUR = (220, 60, 60)
# --- layout --- #
LEFT_MARGIN = 40
TOP_MARGIN = 40
RIGHT_MARGIN = 40
BOTTOM_MARGIN = 40
UI_GAP = 40
# MAP width
MAP_WIDTH = GRID_SIZE * GRID_WIDTH  # 800
MAP_HEIGHT = GRID_SIZE * GRID_HEIGHT  # 800
# map left top corner
MAP_X = LEFT_MARGIN
MAP_Y = TOP_MARGIN
# UI
UI_WIDTH = MAP_WIDTH // 2
UI_HEIGHT = MAP_HEIGHT
UI_X = MAP_X + MAP_WIDTH + UI_GAP
UI_Y = MAP_Y
# screen
SCREEN_WIDTH = LEFT_MARGIN + MAP_WIDTH + UI_GAP + UI_WIDTH + RIGHT_MARGIN
SCREEN_HEIGHT = TOP_MARGIN + MAP_HEIGHT + BOTTOM_MARGIN
# target
# TARGET_SEQUENCE = "ILOVEPYTHONCOMP9001"
TARGET_SEQUENCE = "IL"
